---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: "2.1"
"twitter":
  use: "theme"
production_url : http://oprod.net
base_path: "/"

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'