title : oprod.net
tagline: Blog Tagline
author :
  name : Andrei G
  github : otzy007
  twitter : otzy_007
  feedburner : oprod

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
