title : oprod.net
tagline: Blog Tagline
author :
  name : Andrei G
  github : otzy007
  twitter : otzy_007
  feedburner : oprod

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

plugins:
sitemap_generator: # all optional
file_name: sitemap.xml
exclude_id:
- pages.html
change_frequency_custom_name: changefreq
priority_custom_variable_name: priority
